LOCATIONS = [{"name": "Ukraine",
              "description": "Home. Everything is stable. But something needs to change.",
              "effects": {}},
            {"name": "Istanbul",
             "description": "Flight delayed. One more day in the airport. At least the tea is good.",
             "effects": {"energy": -15, "money": -100, "stress": 10, "coffee": -10}},
             {"name": "Chicago",
              "description": "America. Cold. Loud. Overwhelming. But you`re here.",
              "effects": {"energy": -20, "money": -200, "stress": 10, "knowledge": 5}},
             {"name": "Denver",
              "description": "Mountains. Fresh air. For the first time - you feel like maybe this works.",
              "effects": {"energy": -10, "stress": -10, "coffee": 10}},
             {"name": "Las Vegas",
              "description": "Everything here is designed to distract you. Stay focused.",
              "effects": {"energy": 10, "money": -150, "stress": 15}},
             {"name": "Los Angeles",
              "description": "Everyone here is building something. Time to start.",
              "effects": {"energy": -15, "money": -200, "stress": 10, "knowledge": 10}},
             {"name": "Santa Cruz",
              "description": "Ocean. Dog on the beach. One day just for you.",
              "effects": {"energy": 20, "coffee": 10, "stress": -20}},
             {"name": "Palo Alto",
              "description": "Tech is everywhere here. Your first real interview practice.",
              "effects": {"energy": -10, "stress": 20, "knowledge": 15}},
             {"name": "San Jose",
              "description": "Almost there. One more push.",
              "effects": {"energy": -10, "stress": 5, "coffee": -10, "knowledge": 10}},
             {"name": "San Francisco",
              "description": "This is it. The interview. Everything you worked for.",
              "effects": {}}
           ]